// <auto-generated />
using System;
using CoachFlowApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoachFlowApi.Infrastructure.Migrations
{
    [DbContext(typeof(CoachFlowDbContext))]
    partial class CoachFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoachFlowApi.Domain.Entities.Achat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAchat")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GuideId")
                        .HasColumnType("int");

                    b.Property<int>("PrixAchat")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuideId");

                    b.HasIndex("UserId");

                    b.ToTable("Achats");
                });

            modelBuilder.Entity("CoachFlowApi.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<Guid?>("CoachId1")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateRdv")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Duree")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoachId1");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("CoachFlowApi.Domain.Entities.Coach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("CoachFlowApi.Domain.Entities.Guide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<Guid?>("CoachId1")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDubutant")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LienUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Prix")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CoachId1");

                    b.ToTable("Guides");
                });

            modelBuilder.Entity("CoachFlowApi.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CoachFlowApi.Domain.Entities.Achat", b =>
                {
                    b.HasOne("CoachFlowApi.Domain.Entities.Guide", "Guide")
                        .WithMany("Achats")
                        .HasForeignKey("GuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoachFlowApi.Domain.Entities.User", "User")
                        .WithMany("Achats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guide");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoachFlowApi.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("CoachFlowApi.Domain.Entities.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId1");

                    b.HasOne("CoachFlowApi.Domain.Entities.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoachFlowApi.Domain.Entities.Guide", b =>
                {
                    b.HasOne("CoachFlowApi.Domain.Entities.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId1");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("CoachFlowApi.Domain.Entities.Guide", b =>
                {
                    b.Navigation("Achats");
                });

            modelBuilder.Entity("CoachFlowApi.Domain.Entities.User", b =>
                {
                    b.Navigation("Achats");

                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
